services:
  enshrouded:
    image: enshrouded-windocker:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "America/Chicago"
      NAME: "sPiNtOpOliS"
      WEBHOOK_URL: "${WEBHOOK_URL}"
      AUTO_UPDATE: "true"
      AUTO_UPDATE_SCHEDULE: "0 3 * * *"
      SCHEDULED_RESTART: "true"
      SCHEDULED_RESTART_SCHEDULE: "0 4 * * *"
      # Game Settings
      PLAYER_HEALTH_FACTOR: "1.0"
      PLAYER_MANA_FACTOR: "1.0"
      PLAYER_STAMINA_FACTOR: "1.0"
      PLAYER_BODY_HEAT_FACTOR: "1.0"
      ENABLE_DURABILITY: "true"
      ENABLE_STARVING_DEBUFF: "false"
      FOOD_BUFF_DURATION_FACTOR: "1.0"
      FROM_HUNGER_TO_STARVING: "600000000000"
      SHROUD_TIME_FACTOR: "1.0"
      TOMBSTONE_MODE: "AddBackpackMaterials"
      ENABLE_GLIDER_TURBULENCES: "true"
      WEATHER_FREQUENCY: "Normal"
      MINING_DAMAGE_FACTOR: "1.0"
      PLANT_GROWTH_SPEED_FACTOR: "1.0"
      RESOURCE_DROP_STACK_AMOUNT_FACTOR: "1.0"
      FACTORY_PRODUCTION_SPEED_FACTOR: "1.0"
      PERK_UPGRADE_RECYCLING_FACTOR: "0.8"
      PERK_COST_FACTOR: "1.0"
      EXPERIENCE_COMBAT_FACTOR: "1.0"
      EXPERIENCE_MINING_FACTOR: "1.0"
      EXPERIENCE_EXPLORATION_QUESTS_FACTOR: "1.0"
      RANDOM_SPAWNER_AMOUNT: "Many"
      AGGRO_POOL_AMOUNT: "Normal"
      ENEMY_DAMAGE_FACTOR: "1.0"
      ENEMY_HEALTH_FACTOR: "1.5"
      ENEMY_STAMINA_FACTOR: "0.6"
      ENEMY_PERCEPTION_RANGE_FACTOR: "1.0"
      BOSS_DAMAGE_FACTOR: "1.0"
      BOSS_HEALTH_FACTOR: "2.0"
      THREAT_BONUS: "1.0"
      PACIFY_ALL_ENEMIES: "false"
      TAMING_STARTLE_REPERUSSION: "LoseSomeProgress"
      DAY_TIME_DURATION: "1800000000000"
      NIGHT_TIME_DURATION: "720000000000"
      # User Groups (passwords loaded from .env)
      SET_GROUP_VISITOR_PASSWORD: "${SET_GROUP_VISITOR_PASSWORD}"
      SET_GROUP_VISITOR_CAN_KICK_BAN: "true"
      SET_GROUP_VISITOR_CAN_ACCESS_INVENTORIES: "true"
      SET_GROUP_HELPER_PASSWORD: "${SET_GROUP_HELPER_PASSWORD}"
      SET_GROUP_HELPER_CAN_KICK_BAN: "true"
      SET_GROUP_HELPER_CAN_ACCESS_INVENTORIES: "true"
      SET_GROUP_FRIEND_PASSWORD: "${SET_GROUP_FRIEND_PASSWORD}"
      SET_GROUP_FRIEND_CAN_KICK_BAN: "true"
      SET_GROUP_FRIEND_CAN_ACCESS_INVENTORIES: "true"
      SET_GROUP_ADMIN_PASSWORD: "${SET_GROUP_ADMIN_PASSWORD}"
      SET_GROUP_ADMIN_CAN_KICK_BAN: "true"
      SET_GROUP_ADMIN_CAN_ACCESS_INVENTORIES: "true"
    ports:
      - "15636:15636/udp"
      - "15636:15636/tcp"
      - "15637:15637/udp"
      - "15637:15637/tcp"
    volumes:
      - ../enshrouded:C:\enshrouded
